# Generated by Django 3.2.5 on 2021-07-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10, verbose_name='Método')),
                ('titulo_metodo', models.CharField(max_length=50, unique=True, verbose_name='Título Método')),
                ('request_example', models.TextField(verbose_name='Request Example')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('url', models.URLField(verbose_name='Url')),
                ('response_example', models.TextField(verbose_name='Response Example')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Sección')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='Field')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.endpoint')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.section'),
        ),
    ]
